#!/bin/bash
set -euo pipefail

HOME_DIR="/home/sandbox"

# ============================================================
# First-run initialization
# ============================================================
# This script runs as container ENTRYPOINT.
# Goal: prepare user environment safely, then start requested command.
#
# Important behavior:
# - It copies defaults only when files are missing (first run).
# - It does not overwrite existing user config in persisted home volume.

# Copy one default config file only if destination does not exist.
# src: file baked in image (from /etc/skel)
# dest: file inside persisted user home
copy_default() {
  local src="$1"
  local dest="$2"
  if [[ ! -f "$dest" ]]; then
    echo "[init] Copying default: $dest"
    mkdir -p "$(dirname "$dest")"
    cp "$src" "$dest"
  fi
}

copy_default /etc/skel/.default.zshrc        "$HOME_DIR/.zshrc"
copy_default /etc/skel/.default.zimrc         "$HOME_DIR/.zimrc"
copy_default /etc/skel/.default.tmux.conf     "$HOME_DIR/.tmux.conf"
copy_default /etc/skel/.config/starship.toml  "$HOME_DIR/.config/starship.toml"

# Claude CLI reads this file very early. Ensure it exists to avoid repeated
# ENOENT exceptions during startup when home was freshly initialized/reset.
if [[ ! -f "$HOME_DIR/.claude/remote-settings.json" ]]; then
  mkdir -p "$HOME_DIR/.claude"
  printf '{}\n' > "$HOME_DIR/.claude/remote-settings.json"
fi

# Some networks intermittently corrupt TLS 1.3 record streams for Node clients,
# while curl/OpenSSL still work. Default to a safer Node TLS profile that
# prefers IPv4 and caps TLS to 1.2 unless user explicitly disables this guard.
if [[ "${AGENT_SANDBOX_NODE_TLS_COMPAT:-1}" == "1" ]]; then
  if [[ "${NODE_OPTIONS:-}" != *"--tls-max-v1.2"* ]]; then
    export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--tls-max-v1.2"
  fi
  if [[ "${NODE_OPTIONS:-}" != *"--tls-min-v1.2"* ]]; then
    export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--tls-min-v1.2"
  fi
  if [[ "${NODE_OPTIONS:-}" != *"--dns-result-order=ipv4first"* ]]; then
    export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--dns-result-order=ipv4first"
  fi
fi

# ============================================================
# Zimfw bootstrap
# ============================================================
ZIM_HOME="$HOME_DIR/.zim"

# Download only zimfw core script.
# We intentionally avoid full installer because it can overwrite .zshrc.
if [[ ! -f "$ZIM_HOME/zimfw.zsh" ]]; then
  echo "[init] Downloading zimfw..."
  mkdir -p "$ZIM_HOME"
  curl -fsSL "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh" \
    -o "$ZIM_HOME/zimfw.zsh"
fi

# Install modules only once.
# init.zsh is generated by zimfw install and indicates bootstrap completion.
if [[ -f "$ZIM_HOME/zimfw.zsh" ]]; then
  if [[ ! -f "$ZIM_HOME/init.zsh" ]]; then
    echo "[init] Installing zim modules..."
    # Keep startup resilient: do not fail entire container start on transient network errors.
    ZIM_HOME="$ZIM_HOME" zsh "$ZIM_HOME/zimfw.zsh" install -q || true
  fi
fi

# ============================================================
# One-time tool setup
# ============================================================
# These are idempotent checks: safe across repeated container starts.

# Docker socket access is handled by --group-add in run.sh (no sudo needed)

# Configure git-delta as pager when available.
# We avoid re-writing config every run by checking existing value first.
if command -v delta &>/dev/null; then
  if [[ "$(git config --global core.pager 2>/dev/null)" != "delta" ]]; then
    echo "[init] Configuring git-delta..."
    git config --global core.pager delta
    git config --global interactive.diffFilter 'delta --color-only'
    git config --global delta.navigate true
    git config --global delta.side-by-side true
    git config --global delta.line-numbers true
    git config --global merge.conflictstyle diff3
    git config --global diff.colorMoved default
  fi
fi

# Set default git editor to micro when available and unset.
if command -v micro &>/dev/null; then
  if [[ -z "$(git config --global core.editor 2>/dev/null)" ]]; then
    git config --global core.editor micro
  fi
fi

# Install gh-copilot extension in user scope (inside persisted home).
# This happens once because extension directory is checked first.
if command -v gh &>/dev/null; then
  if [[ ! -d "$HOME_DIR/.local/share/gh/extensions/gh-copilot" ]]; then
    echo "[init] Installing GitHub Copilot CLI..."
    gh extension install github/gh-copilot || true
  fi
fi

# TODO: Re-enable tealdeer cache bootstrap after fixing intermittent
# "InvalidArchive" failures during `tldr --update` in this environment.

# Install broot shell launcher script if broot exists.
if command -v broot &>/dev/null; then
  if [[ ! -f "$HOME_DIR/.config/broot/launcher/bash/br" ]]; then
    echo "[init] Initializing broot..."
    broot --install || true
  fi
fi

# Ensure history file exists for zsh sessions.
touch "$HOME_DIR/.zsh_history"

echo "[init] Agent sandbox ready!"
echo ""

# ============================================================
# Execute CMD
# ============================================================
# Hand control to Docker CMD (default: /bin/zsh).
# Using exec keeps correct signal handling and process tree.
exec "$@"
